### PR TITLE
Add -b/--base-os argument to set OS name

### PR DESCRIPTION
**Pull request by frap129**
This change replaces all instances of `archlinux` in ostree.sh with `${SYSTEM_BASE_NAME}`, configurable via the -b/--base-os argument. This allows for directories with new base OS's (like CachyOS) to be used without modifying the script.

### CODE REVIEW

**Comment by frap129** [comment]
Another change that might be good to make alongside this is separating out the base image from `PODMAN_OPT_BUILDFILE`. If `PODMAN_OPT_BUILDFILE` exists in the environment and includes a reference to the archlinux base image, but `./ostree upgrade -b notarch` is run, it would cause confusion by being based on archlinux but being referenced as something else. Wanted to get your agreement before making that change though, any thoughts?

**Review by GrabbenD — APPROVED** [review]
This will definitely be useful!
Thank you for following the correct syntax 🙂

**Comment by GrabbenD** [comment]
> Wanted to get your agreement before making that change though, any thoughts?

Let's do this in a separate PR

> separating out the base image from PODMAN_OPT_BUILDFILE

Good catch
I can definitely see this being confusing

Avoiding hard-coding `archlinux` was the first step in the right direction  (as I'm planning to add Debian and Artix Linux eventually and speaking of issues, this creates another roadblock being hard-coded package names and package manager in ostree.sh's `ENV_CREATE_DEPS`. I'll try to think more about that later when I get around to doing it).

> If PODMAN_OPT_BUILDFILE exists in the environment and includes a reference to the archlinux base image, but ./ostree upgrade -b notarch is run, it would cause confusion

Yeah this breaks, specifying `-f` and `-b` works while using just `-b` breaks the script.
At the end of the day, the user is supposed to specify a customized build file.

One solution to avoid breakage would be to just hardcode `archlinux` in `PODMAN_OPT_BUILDFILE` as the default value which I'm fine with (but this might become confusing for new users once there's more distro flavors)

Do you have any other idea / good (dynamic) solution in mind which doesn't introduce too much code/logic @frap129 ?

**Comment by frap129** [comment]
I think a good way to handle it would be to split `PODMAN_OPT_BUILDFILE` into two variables, one for things required to build a basic OS image like `archlinux/Containerfile.base` and one for user or host related changes like `Containerfile.host.example`. `-f` would then be used to specify Containerfiles for user/host related changes, and -b would be the way the to choose which container image is used for the base. I would expect the usage to be something like `./ostree.sh upgrade -b archlinux -f ./Containerfile.host.desktop`

**Comment by GrabbenD** [comment]
Gotcha @frap129 
That's definitely a lot cleaner CLI wise

We can try this approach as long as `-b archlinux` isn't hardcoded to look for directories in _this_ repository
Feel free to open a PR and I'll check it out!

**Pull request merged**
